import {
  Bell,
  BookOpen,
  BedDouble,
  CalendarDays,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Settings,
  TrendingUp,
  Users,
  Wallet,
} from 'lucide-react';

export const moduleRegistry = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    group: 'Daily Work',
    icon: LayoutDashboard,
    status: 'active',
    permission: 'dashboard.view',
  },
  {
    id: 'students',
    label: 'Students',
    path: '/students',
    group: 'Daily Work',
    icon: GraduationCap,
    status: 'active',
    permission: 'students.view',
  },
  {
    id: 'calendar',
    label: 'Curriculum',
    path: '/modules/calendar',
    group: 'Daily Work',
    icon: CalendarDays,
    status: 'active',
    permission: 'academicCurriculum.view',
  },
  {
    id: 'academics',
    label: 'Academics',
    path: '/modules/academics',
    group: 'Admin Setup',
    icon: GraduationCap,
    status: 'active',
    permission: 'academics.view',
    hideFromSidebar: true,
  },
  {
    id: 'faculty-staff',
    label: 'Faculty',
    path: '/modules/faculty-staff',
    group: 'Daily Work',
    icon: Users,
    status: 'active',
    permission: 'staff.view',
  },
  {
    id: 'attendance',
    label: 'Attendance',
    path: '/modules/attendance',
    group: 'Daily Work',
    icon: Bell,
    status: 'active',
    permission: 'attendance.view',
  },
  {
    id: 'timetable',
    label: 'Timetable',
    path: '/modules/timetable',
    group: 'Daily Work',
    icon: BookOpen,
    status: 'active',
    permission: 'timetable.view',
  },
  {
    id: 'examination-results',
    label: 'Exams',
    path: '/modules/examination-results',
    group: 'Daily Work',
    icon: TrendingUp,
    status: 'active',
    permission: 'exams.view',
  },
  {
    id: 'user-roles',
    label: 'Users & Roles',
    path: '/modules/user-roles',
    group: 'Admin Setup',
    icon: Settings,
    status: 'active',
    permission: 'users.view',
    hideFromSidebar: true,
  },
  {
    id: 'notice-board',
    label: 'Notice Board',
    path: '/modules/notice-board',
    group: 'Admin Setup',
    icon: Bell,
    status: 'active',
    permission: 'notices.view',
  },
  {
    id: 'document-management',
    label: 'Documents',
    path: '/modules/document-management',
    group: 'Daily Work',
    icon: FileText,
    status: 'active',
    permission: 'documents.view',
  },
  {
    id: 'fees',
    label: 'Payment',
    path: '/modules/fees',
    group: 'Daily Work',
    icon: Wallet,
    status: 'active',
    permission: 'fees.view',
  },
  {
    id: 'hostel-management',
    label: 'Hostel',
    path: '/modules/hostel-management',
    group: 'Daily Work',
    icon: BedDouble,
    status: 'active',
    permission: 'hostel.view',
  },
  {
    id: 'financial-reports',
    label: 'Financial Report',
    path: '/modules/financial-reports',
    group: 'Daily Work',
    icon: TrendingUp,
    status: 'active',
    permission: 'financialReports.view',
  },
  {
    id: 'parent-portal',
    label: 'Parent Portal',
    path: '/modules/parent-portal',
    group: 'Parent Portal',
    icon: Users,
    status: 'active',
    permission: 'parentPortal.view',
    hideFromSidebar: true,
  },
  {
    id: 'settings',
    label: 'Settings',
    path: '/modules/settings',
    group: 'Admin Setup',
    icon: Settings,
    status: 'active',
    permission: 'settings.view',
    footer: true,
  },
];

export function getEnabledModules() {
  return moduleRegistry.filter((module) => module.status !== 'disabled');
}

export function getModuleById(id) {
  return moduleRegistry.find((module) => module.id === id) || null;
}

export function getModuleByPath(path) {
  return moduleRegistry.find((module) => module.path === path) || null;
}

