import {
  Bell,
  BookOpen,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Settings,
  TrendingUp,
  Users,
  Wallet,
} from 'lucide-react';

export const moduleRegistry = [
  {
    id: 'dashboard',
    label: 'Students',
    path: '/students',
    group: 'Academic Management',
    icon: LayoutDashboard,
    status: 'active',
  },
  {
    id: 'academics',
    label: 'Academics',
    path: '/modules/academics',
    group: 'Academic Management',
    icon: GraduationCap,
    status: 'demo',
  },
  {
    id: 'faculty-staff',
    label: 'Faculty & Staff',
    path: '/modules/faculty-staff',
    group: 'Academic Management',
    icon: Users,
    status: 'active',
  },
  {
    id: 'attendance',
    label: 'Attendance',
    path: '/modules/attendance',
    group: 'Academic Management',
    icon: Bell,
    status: 'active',
  },
  {
    id: 'timetable',
    label: 'Timetable',
    path: '/modules/timetable',
    group: 'Academic Management',
    icon: BookOpen,
    status: 'active',
  },
  {
    id: 'examination-results',
    label: 'Exams & Results',
    path: '/modules/examination-results',
    group: 'Academic Management',
    icon: TrendingUp,
    status: 'active',
  },
  {
    id: 'user-roles',
    label: 'Users & Roles',
    path: '/modules/user-roles',
    group: 'Administration & Operations',
    icon: Settings,
    status: 'active',
  },
  {
    id: 'notice-board',
    label: 'Notice Board',
    path: '/modules/notice-board',
    group: 'Administration & Operations',
    icon: Bell,
    status: 'active',
  },
  {
    id: 'document-management',
    label: 'Documents',
    path: '/modules/document-management',
    group: 'Administration & Operations',
    icon: FileText,
    status: 'active',
  },
  {
    id: 'fees',
    label: 'Fees',
    path: '/modules/fees',
    group: 'Finance Management',
    icon: Wallet,
    status: 'active',
  },
  {
    id: 'financial-reports',
    label: 'Financial Reports',
    path: '/modules/financial-reports',
    group: 'Finance Management',
    icon: TrendingUp,
    status: 'active',
  },
  {
    id: 'parent-portal',
    label: 'Parent Portal',
    path: '/modules/parent-portal',
    group: 'Parent Portal',
    icon: Users,
    status: 'active',
  },
  {
    id: 'settings',
    label: 'Settings',
    path: '/modules/settings',
    group: 'Administration & Operations',
    icon: Settings,
    status: 'demo',
  },
];

export function getEnabledModules() {
  return moduleRegistry.filter((module) => module.status !== 'disabled');
}

