export const demoStudents = [
  {
    id: 'demo-4449',
    admissionNo: 'ADM-2026-04449',
    studentId: 'STU-4449',
    name: 'Vivek Sharma',
    className: 'Class XII',
    section: 'A',
    program: 'CBSE Science',
    institute: 'Maurya Institute of Allied Health Sciences',
    guardianName: 'Rajesh Sharma',
    idHolder: 'Vivek Sharma',
    academicYear: '2026-2027',
    phone: '+91 98765 43210',
    email: 'vivek.sharma@student.genius.edu',
    status: 'Active',
    documents: ['Aadhaar Card', 'Marks Card', 'Transfer Certificate'],
    promotionStatus: 'Eligible',
    transferStatus: 'Not Requested',
    createdAtText: '03 Jun 2026',
  },
  {
    id: 'demo-4450',
    admissionNo: 'ADM-2026-04450',
    studentId: 'STU-4450',
    name: 'Vaibhavi Aggarwal',
    className: 'Class XI',
    section: 'B',
    program: 'PU Commerce',
    institute: 'Maurya Institute of Allied Health Sciences',
    guardianName: 'Anita Aggarwal',
    idHolder: 'Vaibhavi Aggarwal',
    academicYear: '2026-2027',
    phone: '+91 99887 77665',
    email: 'vaibhavi@student.genius.edu',
    status: 'Admission Review',
    documents: ['Aadhaar Card', 'Admission Form'],
    promotionStatus: 'Pending Review',
    transferStatus: 'Not Requested',
    createdAtText: '01 Jun 2026',
  },
  {
    id: 'demo-4451',
    admissionNo: 'ADM-2026-04451',
    studentId: 'STU-4451',
    name: 'Aditya Rao',
    className: 'Class X',
    section: 'C',
    program: 'CBSE General',
    institute: 'Maurya Institute of Allied Health Sciences',
    guardianName: 'Meera Rao',
    idHolder: 'Aditya Rao',
    academicYear: '2025-2026',
    phone: '+91 91234 56780',
    email: 'aditya.rao@student.genius.edu',
    status: 'Active',
    documents: ['Aadhaar Card', 'Birth Certificate', 'Previous School Record'],
    promotionStatus: 'Eligible',
    transferStatus: 'Certificate Ready',
    createdAtText: '29 May 2026',
  },
];
