export const demoNoticeItems = [
  {
    id: 'demo-notice-1',
    type: 'Digital Notice',
    title: 'Library timing update',
    referenceNo: 'NOTICE-2026-001',
    audience: 'Students',
    priority: 'Normal',
    body: 'Library hours are extended until 6 PM during the revision week.',
    publishDate: '2026-06-18',
    expiryDate: '2026-06-30',
    status: 'Published',
    createdByName: 'Admin Office',
    createdAtText: '18 Jun 2026',
  },
  {
    id: 'demo-notice-2',
    type: 'Circular',
    title: 'Faculty meeting circular',
    referenceNo: 'CIR-2026-014',
    audience: 'Faculty',
    priority: 'Important',
    body: 'All faculty members are requested to attend the academic review meeting.',
    publishDate: '2026-06-20',
    expiryDate: '2026-06-22',
    status: 'Draft',
    createdByName: 'Principal Office',
    createdAtText: '19 Jun 2026',
  },
  {
    id: 'demo-notice-3',
    type: 'Event Announcement',
    title: 'Annual sports day',
    referenceNo: 'EVENT-2026-006',
    audience: 'All',
    priority: 'Urgent',
    body: 'Annual sports day registrations close this week.',
    publishDate: '2026-06-19',
    expiryDate: '2026-07-05',
    status: 'Published',
    createdByName: 'Activities Department',
    createdAtText: '19 Jun 2026',
  },
];
