const topicSets = {
  alliedAnatomy: [
    'Introduction to anatomy and anatomical terminology',
    'Cell, tissues, epithelium, connective tissue, cartilage and bone',
    'Skeletal system, bones, joints and muscles',
    'Cardiovascular system and major blood vessels',
    'Gastro-intestinal system',
    'Respiratory system',
    'Urinary system',
    'Male and female reproductive system',
    'Endocrine glands',
    'Nervous system and cranial nerves',
    'Sensory organs',
    'Basic embryology',
  ],
  alliedPhysiology: [
    'General physiology and transport across cell membrane',
    'Blood, plasma proteins, blood groups and immunity',
    'Nerve and muscle physiology',
    'Cardiovascular physiology',
    'Respiratory physiology',
    'Digestive system physiology',
    'Renal physiology and body fluids',
    'Endocrine physiology',
    'Reproductive physiology',
    'Central nervous system and special senses',
    'Body temperature regulation',
  ],
  alliedBiochemistry: [
    'Cell chemistry, water, electrolytes and pH',
    'Carbohydrates and carbohydrate metabolism',
    'Lipids and lipid metabolism',
    'Proteins, amino acids and protein metabolism',
    'Enzymes and coenzymes',
    'Vitamins and minerals',
    'Nutrition and energy metabolism',
    'Nucleic acids and genetic material',
    'Liver function, kidney function and clinical biochemistry',
    'Laboratory units, measurements and quality control',
  ],
  alliedPathology: [
    'Introduction to clinical pathology',
    'Urine examination and body fluid analysis',
    'Stool examination and parasites',
    'Hematology and complete blood count',
    'Coagulation and hemostasis',
    'Blood grouping and blood banking',
    'Cell injury, inflammation and repair',
    'Neoplasia and tumor pathology',
    'Histopathology techniques and staining',
    'Cytology and specimen handling',
  ],
  alliedMicrobiology: [
    'History and scope of microbiology',
    'Microscopy, staining and morphology of microorganisms',
    'Bacteriology and culture media',
    'Sterilization, disinfection and biomedical waste',
    'Immunity, antigens, antibodies and vaccines',
    'Virology, mycology and parasitology basics',
    'Specimen collection and transport',
    'Antimicrobial susceptibility testing',
    'Hospital infection control',
  ],
  english: [
    'Introduction to communication',
    'Applied grammar',
    'Written composition',
    'Reading and comprehension',
    'Forms of composition',
    'Verbal communication and presentation',
  ],
  kannada: [
    'Functional Kannada communication',
    'Reading and comprehension',
    'Writing practice',
    'Health care vocabulary',
    'Patient and community communication',
  ],
  healthCare: [
    'Health, illness and levels of prevention',
    'Hospital departments and patient care areas',
    'Basic first aid and emergency response',
    'Infection control and biomedical waste',
    'Patient safety and communication',
    'Community health concepts',
  ],
  sociology: [
    'Sociology, society and social process',
    'Social institutions, family and community',
    'Rural, urban and tribal communities',
    'Social change and social problems',
    'Health hazards in communities',
    'Culture, socialization and health behavior',
  ],
  constitution: [
    'Meaning and making of the Indian Constitution',
    'Democratic institutions and federal structure',
    'Fundamental rights and duties',
    'Directive principles of state policy',
    'Special constitutional rights and safeguards',
    'Separation of powers',
    'Election Commission and public service commissions',
    'Amendment procedure and writs',
  ],
  environmentalHealth: [
    'Environment and ecosystem health',
    'Water, air and soil pollution',
    'Sanitation and waste disposal',
    'Occupational and community health hazards',
    'Climate change and sustainable development',
    'Health indicators and public health monitoring',
  ],
  ethicsDatabase: [
    'Ethics in health care practice',
    'Confidentiality and consent',
    'Professional conduct and accountability',
    'Health records and database basics',
    'Data entry, storage and retrieval',
    'Computerized laboratory or hospital information systems',
  ],
  researchBiostatistics: [
    'Introduction to research methodology',
    'Data collection and tabulation',
    'Measures of central tendency',
    'Measures of variability',
    'Probability and standard distributions',
    'Sampling techniques',
    'Health indicators',
    'Presentation and interpretation of results',
  ],
  computerApplication: [
    'Computer fundamentals',
    'Operating systems and office tools',
    'Data entry and spreadsheets',
    'Hospital and laboratory information systems',
    'Internet, email and online safety',
    'Basic data security',
  ],
  aottMedicine: [
    'Pre-operative medical assessment',
    'Cardiovascular diseases relevant to anaesthesia',
    'Respiratory diseases and pulmonary function',
    'Renal physiology and renal disease',
    'Endocrine and metabolic disorders',
    'Fluid, electrolyte and acid-base balance',
    'Shock, sepsis and emergency medicine',
    'Critical care principles',
  ],
  aottAppliedPathMicro: [
    'Clinical pathology and hematology for perioperative care',
    'Inflammation, infection and wound healing',
    'Microbiology of operation theatre environment',
    'Sterilization, disinfection and CSSD workflow',
    'Specimen collection and transport',
    'Blood grouping, cross matching and transfusion safety',
    'Air, surface and water sampling in OT',
    'Biomedical waste management',
  ],
  aottPharmacology: [
    'General pharmacology and routes of administration',
    'Drugs used in anaesthesia',
    'Sedatives, analgesics and opioids',
    'Muscle relaxants and reversal agents',
    'Local anaesthetics',
    'Emergency drugs and resuscitation medicines',
    'Autonomic and cardiovascular drugs',
    'IV fluids, blood products and drug calculations',
    'Adverse drug reactions and interactions',
  ],
  aottIntro: [
    'Operation theatre layout and zoning',
    'OT table, lights and basic equipment',
    'Sterilization and disinfection practices',
    'Anaesthesia machine components and safety features',
    'Airway equipment and oxygen delivery devices',
    'Patient monitoring in anaesthesia',
    'General anaesthesia techniques',
    'Regional anaesthesia techniques',
    'Surgical instruments and electrosurgical unit',
    'Laparoscopy unit and endoscopy equipment',
    'Post-anaesthesia care unit',
    'Principles of monitored anaesthesia care',
  ],
  aottClinical: [
    'Pre-anaesthetic evaluation and consent',
    'Airway assessment and airway management',
    'Monitoring standards during anaesthesia',
    'Anaesthesia for general surgery',
    'Anaesthesia for obstetric and gynecological procedures',
    'Anaesthesia for pediatric and geriatric patients',
    'Fluid therapy and blood transfusion in theatre',
    'Emergency management in operation theatre',
    'Documentation and handover',
  ],
  aottApplied: [
    'Anaesthesia outside the operating room',
    'Anaesthesia in MRI, CT and cath lab',
    'Intensive care unit setup and monitoring',
    'Mechanical ventilation basics',
    'Pain management and analgesia services',
    'Post-anaesthesia recovery and complications',
    'Difficult airway and equipment troubleshooting',
    'Patient transport and transfer safety',
  ],
  aottAdvanced: [
    'Advanced monitoring and tissue oxygenation',
    'Arterial blood gas interpretation',
    'Shock, sepsis and multi-organ dysfunction',
    'Trauma, burns and emergency anaesthesia support',
    'Ventilator modes and respiratory failure',
    'Bedside ultrasound and radiologic imaging in ICU',
    'Infection control in critical care',
    'Quality assurance and safety protocols',
  ],
  mitRadiationPhysics: [
    'Electromagnetic radiation and x-rays',
    'X-ray production and tube design',
    'Interaction of radiation with matter',
    'Radiation quantities and units',
    'Beam quality, filtration and attenuation',
    'Radiation absorption and image formation',
    'Biological effects of radiation',
  ],
  mitRadiationSafety: [
    'Aim and principles of radiation protection',
    'Dose limits and occupational exposure',
    'Protection from primary, scatter and leakage radiation',
    'Shielding, distance and time principles',
    'Radiation monitoring instruments',
    'Radiation warning signs and controlled areas',
    'Regulatory requirements and safe work practice',
  ],
  mitDarkroom: [
    'Radiographic image quality',
    'Image geometry and sharpness',
    'Screens, cassettes and grids',
    'Films, processing and darkroom design',
    'Artifacts and quality assurance',
    'Scattered radiation and image contrast',
    'Digital radiography basics',
  ],
  mitPositioning: [
    'Radiographic anatomy and patient positioning basics',
    'Upper limb positioning',
    'Lower limb positioning',
    'Chest and ribs positioning',
    'Spine and pelvis positioning',
    'Skull and facial bones positioning',
    'Abdomen and urinary tract positioning',
    'Contrast and special routine positioning',
    'Radiation protection during positioning',
  ],
  mitDiagnosticImaging: [
    'Computed tomography principles and protocols',
    'Ultrasound and Doppler imaging',
    'Nuclear medicine imaging',
    'Magnetic resonance imaging principles',
    'MRI pulse sequences and image contrast',
    'Vascular and cardiac imaging',
    'Mammography and special modalities',
    'Advanced imaging techniques',
    'Imaging protocol selection and quality assurance',
  ],
  mitSpecialProcedures: [
    'Patient preparation and consent for special procedures',
    'Contrast media and adverse reactions',
    'Fluoroscopy and angiographic procedures',
    'Gastro-intestinal and urinary tract special studies',
    'Emergency care in imaging department',
    'Infection control and patient transfer',
    'Imaging technologist responsibilities',
    'Radiation safety in special procedures',
  ],
  mltBiochemistry2: [
    'Clinical biochemistry laboratory organization',
    'Glassware, reagents and solution preparation',
    'Centrifuges and laboratory equipment',
    'Units of measurement and SI conversion',
    'Carbohydrate metabolism and testing',
    'Lipid profile and lipid metabolism',
    'Protein and amino acid analysis',
    'Enzymology and clinical enzymes',
    'Renal and liver function tests',
    'Quality control and automation',
  ],
  mltBiochemistry3: [
    'Plasma enzymes and diagnostic enzymology',
    'Cardiac markers and organ function tests',
    'Endocrine function testing',
    'Electrolytes, blood gases and acid-base balance',
    'Tumor markers and therapeutic drug monitoring',
    'Clinical toxicology',
    'Advanced automation and analyzer maintenance',
    'Laboratory quality assurance',
  ],
  mltMicrobiology2: [
    'Specimen collection and processing',
    'Staining methods and microscopy',
    'Culture media preparation',
    'Sterilization and disinfection',
    'Bacterial identification methods',
    'Antimicrobial susceptibility testing',
    'Mycology and parasitology basics',
    'Virology basics',
    'Quality control in microbiology laboratory',
  ],
  mltMicrobiology3: [
    'Innate and acquired immunity',
    'Humoral and cell mediated immunity',
    'Hypersensitivity and autoimmunity',
    'Transplantation and tumor immunity',
    'Serological tests',
    'Molecular microbiology methods',
    'Hospital infection control',
    'Vaccines and immunoprophylaxis',
  ],
  mltPathology2: [
    'Histopathology laboratory organization',
    'Fixation, processing and embedding',
    'Microtomy and section cutting',
    'Hematoxylin and eosin staining',
    'Special stains',
    'Hematology techniques',
    'Blood cell morphology',
    'Coagulation tests',
    'Computers in pathology laboratory',
  ],
  mltPathology3: [
    'Advanced hematology',
    'Bone marrow examination',
    'Cytopathology techniques',
    'Histopathology special procedures',
    'Immunohistochemistry basics',
    'Blood banking and transfusion practice',
    'Laboratory safety and quality assurance',
    'Reporting and documentation',
  ],
  bptAnatomy: [
    'General anatomy and histology',
    'Upper limb anatomy',
    'Lower limb anatomy',
    'Thorax, abdomen and pelvis',
    'Head, neck and brain',
    'Neuroanatomy',
    'Embryology and genetics basics',
    'Surface anatomy for physiotherapy',
  ],
  bptPhysiology: [
    'Cell physiology and blood',
    'Nerve and muscle physiology',
    'Cardiovascular system',
    'Respiratory system',
    'Renal system',
    'Digestive system and metabolism',
    'Endocrine system',
    'Central nervous system',
    'Exercise physiology basics',
  ],
  bptBiomechanics: [
    'Mechanics and biomechanical principles',
    'Joint structure and function',
    'Muscle mechanics and kinesiology',
    'Posture and balance',
    'Gait analysis',
    'Upper limb biomechanics',
    'Lower limb biomechanics',
    'Spine biomechanics',
    'Ergonomics and functional movement',
  ],
  bptExerciseTherapy: [
    'Therapeutic exercise principles',
    'Range of motion exercises',
    'Stretching and flexibility',
    'Strengthening techniques',
    'Posture correction',
    'Balance and coordination training',
    'Gait training',
    'Breathing exercises',
    'Exercise prescription and progression',
  ],
  bptElectrotherapy: [
    'Electrical stimulation principles',
    'Low frequency currents',
    'Medium frequency currents',
    'High frequency therapy',
    'Ultrasound therapy',
    'Infrared and ultraviolet radiation',
    'Laser and advanced modalities',
    'Safety, indications and contraindications',
  ],
  bptGeneralMedicine: [
    'Cardiovascular disorders',
    'Respiratory disorders',
    'Neurological medical conditions',
    'Endocrine and metabolic disorders',
    'Rheumatology and geriatrics',
    'Intensive care and medical emergencies',
  ],
  bptGeneralSurgery: [
    'General surgical conditions',
    'Wound healing and burns',
    'Cardiothoracic surgery',
    'Neurosurgery basics',
    'Plastic and reconstructive surgery',
    'Post-operative physiotherapy care',
  ],
  bptOrthopedics: [
    'Fractures and dislocations',
    'Soft tissue injuries',
    'Degenerative joint disorders',
    'Spinal disorders',
    'Orthopedic surgery and implants',
    'Amputation and prosthetic principles',
  ],
  bptMusculoskeletal: [
    'Musculoskeletal assessment',
    'Manual therapy basics',
    'Therapeutic exercise for orthopedic conditions',
    'Sports injury prevention and rehabilitation',
    'Pain management',
    'Functional training and return to activity',
  ],
  bptCardiorespiratory: [
    'Cardiorespiratory assessment',
    'Breathing exercises and airway clearance',
    'Chest physiotherapy',
    'ICU physiotherapy',
    'Cardiac rehabilitation',
    'Pulmonary rehabilitation',
  ],
  bptNeuroPhysio: [
    'Neurological assessment',
    'Motor control and neuroplasticity',
    'Stroke rehabilitation',
    'Spinal cord injury rehabilitation',
    'Pediatric neurological conditions',
    'Balance, gait and functional training',
  ],
  bptCommunityRehab: [
    'Community based rehabilitation concepts',
    'Disability prevention and screening',
    'Home exercise programs',
    'Assistive devices and accessibility',
    'Health education and community participation',
    'Vocational rehabilitation',
  ],
  botIntro: [
    'History, philosophy and scope of occupational therapy',
    'Occupational performance and activity analysis',
    'Therapeutic use of self and therapeutic relationship',
    'Frames of reference and models of practice',
    'OT process, assessment and goal setting',
    'Professional ethics and documentation',
  ],
  botBasics: [
    'Occupational therapy process',
    'Activity analysis and grading',
    'Therapeutic media and purposeful activity',
    'Group dynamics and therapeutic groups',
    'ADL training and functional independence',
    'Documentation, progress notes and discharge planning',
  ],
  botBiomechanics: [
    'Biomechanical principles in OT',
    'Upper limb and hand function',
    'Lower limb and posture mechanics',
    'Ergotherapeutics and work simplification',
    'Splinting principles',
    'Joint protection and energy conservation',
    'Ergonomic assessment',
  ],
  botMedicalDisorders: [
    'Common medical conditions relevant to OT',
    'Cardiorespiratory disorders',
    'Neurological medical conditions',
    'Metabolic and endocrine disorders',
    'Geriatric and chronic illness care',
    'Functional implications of disease',
  ],
  botSurgicalDisorders: [
    'Common surgical conditions',
    'Wound healing, burns and scars',
    'Plastic and reconstructive surgery',
    'General surgery and post-operative care',
    'Hand surgery basics',
    'OT role in surgical rehabilitation',
  ],
  botMedicalConditions: [
    'OT assessment in medical conditions',
    'Cardiopulmonary rehabilitation',
    'Neurological medical rehabilitation',
    'Geriatric rehabilitation',
    'Energy conservation and work simplification',
    'Patient and caregiver education',
  ],
  botSurgicalConditions: [
    'OT in burns and plastic surgery',
    'Hand rehabilitation',
    'Post-operative functional training',
    'Scar management and splinting',
    'ADL retraining after surgery',
    'Return to work planning',
  ],
  botOrthopaedicConditions: [
    'Orthopedic assessment for OT',
    'Fractures, dislocations and joint disorders',
    'Splints, orthoses and assistive devices',
    'Upper limb rehabilitation',
    'ADL and functional mobility training',
    'Home and workplace modification',
  ],
  botPaediatricConditions: [
    'Developmental milestones',
    'Pediatric assessment tools',
    'Cerebral palsy and developmental delay',
    'Sensory integration basics',
    'Play and school based intervention',
    'Family centered care',
  ],
  botMentalHealth: [
    'Mental health assessment in OT',
    'Psychiatric conditions and functional impact',
    'Therapeutic groups and activity programs',
    'Behavioral and cognitive approaches',
    'Community mental health',
    'Recovery, participation and vocational skills',
  ],
  botNeurologicalConditions: [
    'Neurological assessment in OT',
    'Stroke and traumatic brain injury',
    'Spinal cord injury',
    'Peripheral nerve injuries',
    'Cognitive and perceptual retraining',
    'Functional mobility and ADL adaptation',
  ],
  botOrthoticsAssistive: [
    'Orthotics principles',
    'Assistive technology selection',
    'Wheelchairs and mobility aids',
    'Adaptive devices for ADL',
    'Environmental control and accessibility',
    'Training, maintenance and follow-up',
  ],
  botPracticeIssues: [
    'Professional practice and ethics',
    'Documentation and outcome measurement',
    'Interdisciplinary teamwork',
    'Program planning and service delivery',
    'Evidence based OT practice',
    'Administration and quality assurance',
  ],
  botErgonomics: [
    'Ergonomic principles',
    'Workstation assessment',
    'Manual handling and injury prevention',
    'Work simplification and energy conservation',
    'Industrial ergonomics',
    'Return to work and vocational rehabilitation',
  ],
  bscnFoundation1: [
    'Nursing as a profession',
    'Hospital admission, transfer and discharge',
    'Communication and nurse-patient relationship',
    'Vital signs and health assessment basics',
    'Hygiene, comfort and safety',
    'Infection control and biomedical waste',
    'First aid and basic emergency care',
    'Medication safety basics',
    'Documentation and nursing process',
  ],
  bscnFoundation2: [
    'Health assessment and physical examination',
    'Nursing process and care planning',
    'Admission, discharge and continuity of care',
    'Nutrition, elimination and personal hygiene care',
    'Medication administration',
    'Wound care and asepsis',
    'Oxygenation and basic procedures',
    'Patient education and documentation',
  ],
  bscnAdultHealth1: [
    'Pathophysiology concepts',
    'Care of patients with respiratory disorders',
    'Care of patients with cardiovascular disorders',
    'Care of patients with blood and immune disorders',
    'Care of patients with gastro-intestinal disorders',
    'Perioperative nursing',
    'BCLS and emergency response',
    'Clinical skills and case documentation',
  ],
  bscnAdultHealth2: [
    'Care of patients with renal and urinary disorders',
    'Endocrine and metabolic disorders',
    'Neurological disorders',
    'Musculoskeletal disorders',
    'Critical care and emergency nursing',
    'Geriatric nursing',
    'Palliative care',
    'Rehabilitation and discharge planning',
  ],
  bscnChildHealth1: [
    'Growth and development',
    'Newborn and infant care',
    'Essential newborn care',
    'Nutrition and immunization',
    'Common pediatric illnesses',
    'Pediatric procedures and safety',
    'Family centered nursing care',
  ],
  bscnChildHealth2: [
    'High risk newborn and neonatal care',
    'Pediatric medical and surgical conditions',
    'IMNCI and child health programs',
    'Pediatric emergencies',
    'Developmental disorders',
    'Pediatric rehabilitation and family education',
  ],
  bscnMentalHealth1: [
    'Principles of mental health nursing',
    'Therapeutic communication',
    'Assessment of mental status',
    'Anxiety, mood and psychotic disorders',
    'Substance use disorders',
    'Psychiatric emergencies',
    'Milieu therapy and safety',
  ],
  bscnMentalHealth2: [
    'Advanced psychiatric nursing care',
    'Child and adolescent mental health',
    'Community mental health nursing',
    'Psychotherapies and counseling',
    'Rehabilitation and de-addiction',
    'Legal and ethical issues in mental health',
  ],
  bscnCommunity1: [
    'Concepts of community health nursing',
    'Environmental health and epidemiology',
    'Family health assessment',
    'Maternal and child health services',
    'National health programs',
    'Communicable disease control',
    'Health education and home visits',
  ],
  bscnCommunity2: [
    'Community health nursing process',
    'Primary health care and public health system',
    'Occupational health',
    'School health services',
    'Disaster nursing',
    'Urban and rural health services',
    'Program planning, monitoring and evaluation',
  ],
  bscnMidwifery1: [
    'Anatomy and physiology of reproductive system',
    'Antenatal assessment and care',
    'Normal pregnancy',
    'Normal labor and delivery',
    'Immediate newborn care',
    'Postnatal care',
    'SBA module and safe birth practices',
  ],
  bscnMidwifery2: [
    'High risk pregnancy',
    'Complications of labor',
    'Obstetric emergencies',
    'Gynecological nursing',
    'Family planning',
    'Safe delivery app module',
    'Referral, documentation and newborn follow-up',
  ],
  bscnManagement: [
    'Leadership theories and styles',
    'Ward management and delegation',
    'Quality assurance in nursing',
    'Human resource management',
    'Budgeting and inventory',
    'Legal responsibilities',
    'Supervision, reporting and records',
  ],
  bscnResearch: [
    'Research problem and literature review',
    'Research designs',
    'Sampling and data collection',
    'Statistics and data analysis',
    'Ethics in nursing research',
    'Writing research proposal and report',
    'Evidence based nursing practice',
  ],
  internship: [
    'Clinical posting orientation',
    'Supervised patient care',
    'Case assessment and documentation',
    'Skill performance and competency log',
    'Interdisciplinary communication',
    'Clinical handover and reflective practice',
  ],
};

const genericCodeTopics = {
  'ANAT-Y1': topicSets.alliedAnatomy,
  'PHYS-Y1': topicSets.alliedPhysiology,
  'BIOC-Y1': topicSets.alliedBiochemistry,
  'PATH-Y1': topicSets.alliedPathology,
  'MICR-Y1': topicSets.alliedMicrobiology,
  'ENG-Y1': topicSets.english,
  'KAN-Y1': topicSets.kannada,
  'HC-Y1': topicSets.healthCare,
  'SOC-Y1': topicSets.sociology,
  'SOC-Y2': topicSets.sociology,
  'COI-Y2': topicSets.constitution,
  'ENV-Y2': topicSets.environmentalHealth,
  'EDM-Y3': topicSets.ethicsDatabase,
  'RBS-Y3': topicSets.researchBiostatistics,
  'COMP-Y3': topicSets.computerApplication,
};

const curriculumCodeTopics = {
  'AOTT:MED-AOTT-Y2': topicSets.aottMedicine,
  'AOTT:APPMIC-Y2': topicSets.aottAppliedPathMicro,
  'AOTT:PHAR-Y2': topicSets.aottPharmacology,
  'AOTT:IAOTT-Y2': topicSets.aottIntro,
  'AOTT:AOTT-CL-Y3': topicSets.aottClinical,
  'AOTT:AOTT-AP-Y3': topicSets.aottApplied,
  'AOTT:AOTT-ADV-Y3': topicSets.aottAdvanced,

  'MIT:RADPHY-Y2': [...topicSets.mitRadiationPhysics, ...topicSets.mitRadiationSafety],
  'MIT:IMGDR-Y2': topicSets.mitDarkroom,
  'MIT:RADPOS-Y2': topicSets.mitPositioning,
  'MIT:DIAGIMG-Y3': topicSets.mitDiagnosticImaging,
  'MIT:RADSPC-Y3': topicSets.mitSpecialProcedures,
  'MIT:RADPRA-Y3': topicSets.mitPositioning,

  'MLT:BIOC-Y2': topicSets.mltBiochemistry2,
  'MLT:BIOC-Y3': topicSets.mltBiochemistry3,
  'MLT:MICR-Y2': topicSets.mltMicrobiology2,
  'MLT:MICR-Y3': topicSets.mltMicrobiology3,
  'MLT:PATH-Y2': topicSets.mltPathology2,
  'MLT:PATH-Y3': topicSets.mltPathology3,

  'BPT:ANAT-Y1': topicSets.bptAnatomy,
  'BPT:PHYS-Y1': topicSets.bptPhysiology,
  'BPT:BIOC-Y1': topicSets.alliedBiochemistry,
  'BPT:BIOM-Y1': topicSets.bptBiomechanics,
  'BPT:PSYC-Y1': ['Introduction to psychology', 'Developmental psychology', 'Learning, memory and motivation', 'Personality and behavior', 'Stress, coping and adjustment', 'Psychology in patient care'],
  'BPT:SOC-Y1': topicSets.sociology,
  'BPT:BASN-Y1': ['Basic nursing principles', 'Patient hygiene and comfort', 'Vital signs', 'Bed making and positioning', 'First aid', 'Infection control'],
  'BPT:ORPT-Y1': ['History and scope of physiotherapy', 'Physiotherapy ethics', 'Team roles in rehabilitation', 'Patient communication', 'Professional documentation'],
  'BPT:PBL-Y1': ['Integrated seminar orientation', 'Problem based learning process', 'Case discussion', 'Group presentation', 'Reflective learning log'],
  'BPT:PATH-Y2': topicSets.alliedPathology,
  'BPT:MICR-Y2': topicSets.alliedMicrobiology,
  'BPT:PHAR-Y2': topicSets.aottPharmacology,
  'BPT:EXTH-Y2': topicSets.bptExerciseTherapy,
  'BPT:ELTH-Y2': topicSets.bptElectrotherapy,
  'BPT:ETHA-Y2': ['Professional ethics', 'Administrative records', 'Consent and confidentiality', 'Patient rights', 'Clinical documentation', 'Department organization'],
  'BPT:FACP-Y2': ['First aid principles', 'CPR and BLS', 'Emergency assessment', 'Wounds and bleeding', 'Fractures and transport', 'Shock and burns'],
  'BPT:INTT-Y2': ['Treatment planning', 'Assessment before treatment', 'Therapeutic positioning', 'Progression and precautions', 'Home advice'],
  'BPT:CLOP-Y2': topicSets.internship,
  'BPT:GMED-Y3': topicSets.bptGeneralMedicine,
  'BPT:GSUR-Y3': topicSets.bptGeneralSurgery,
  'BPT:ORTH-Y3': topicSets.bptOrthopedics,
  'BPT:MSPT-Y3': topicSets.bptMusculoskeletal,
  'BPT:CRGP-Y3': topicSets.bptCardiorespiratory,
  'BPT:SRCT1-Y3': topicSets.internship,
  'BPT:ALLT-Y3': ['Allied rehabilitation therapies', 'Yoga and relaxation', 'Occupational therapy basics', 'Speech therapy basics', 'Counseling and referral'],
  'BPT:NEUR-Y4': ['Neuroanatomy review', 'Neurological examination', 'Stroke and movement disorders', 'Spinal cord injury', 'Peripheral nerve lesions', 'Neurosurgical conditions'],
  'BPT:CMED-Y4': topicSets.environmentalHealth,
  'BPT:NPHY-Y4': topicSets.bptNeuroPhysio,
  'BPT:CBR-Y4': topicSets.bptCommunityRehab,
  'BPT:RMB-Y4': topicSets.researchBiostatistics,
  'BPT:SRCT2-Y4': topicSets.internship,
  'BPT:EBPP-Y4': ['Evidence based practice', 'Clinical question framing', 'Literature search', 'Critical appraisal', 'Applying evidence to patient care'],
  'BPT:PROJ-Y4': ['Project planning', 'Data collection', 'Analysis', 'Report writing', 'Presentation'],

  'BOT:HA1': topicSets.alliedAnatomy,
  'BOT:HA2': topicSets.bptAnatomy,
  'BOT:HP1': topicSets.alliedPhysiology,
  'BOT:HP2': topicSets.bptPhysiology,
  'BOT:IOT1': topicSets.botIntro,
  'BOT:BIOC1': topicSets.alliedBiochemistry,
  'BOT:ENG1': topicSets.english,
  'BOT:KAN1': topicSets.kannada,
  'BOT:BOT1': topicSets.botBasics,
  'BOT:BOT2': topicSets.botBasics,
  'BOT:CLIN1': topicSets.internship,
  'BOT:BFA2': ['First aid principles', 'CPR and emergency response', 'Bleeding, wounds and bandaging', 'Fractures and transport', 'Burns, poisoning and shock'],
  'BOT:SOC2': topicSets.sociology,
  'BOT:COI2': topicSets.constitution,
  'BOT:CLIN2': topicSets.internship,
  'BOT:BIOER3': topicSets.botBiomechanics,
  'BOT:BIOER4': topicSets.botBiomechanics,
  'BOT:PATHMIC3': [...topicSets.alliedPathology, ...topicSets.alliedMicrobiology.slice(0, 5)],
  'BOT:PHAR3': topicSets.aottPharmacology,
  'BOT:COMP3': topicSets.computerApplication,
  'BOT:HC3': topicSets.healthCare,
  'BOT:CLIN3': topicSets.internship,
  'BOT:BMD4': topicSets.botMedicalDisorders,
  'BOT:BSD4': topicSets.botSurgicalDisorders,
  'BOT:PSYC4': ['General psychology', 'Developmental psychology', 'Learning and behavior', 'Motivation and emotion', 'Personality', 'Psychological assessment basics'],
  'BOT:ENV4': topicSets.environmentalHealth,
  'BOT:CLIN4': topicSets.internship,
  'BOT:OTMC5': topicSets.botMedicalConditions,
  'BOT:OTSC5': topicSets.botSurgicalConditions,
  'BOT:BORTH5': topicSets.bptOrthopedics,
  'BOT:BPED5': topicSets.botPaediatricConditions,
  'BOT:METH5': ['Medical ethics', 'Consent and confidentiality', 'Professional boundaries', 'Patient rights', 'Ethical decision making'],
  'BOT:CLIN5': topicSets.internship,
  'BOT:OTORTH6': topicSets.botOrthopaedicConditions,
  'BOT:OTPED6': topicSets.botPaediatricConditions,
  'BOT:BPSY6': ['Psychiatric disorders overview', 'Mental status examination', 'Psychopharmacology basics', 'Therapeutic communication', 'Crisis and safety management'],
  'BOT:BNEU6': ['Neurological examination', 'Stroke', 'Traumatic brain injury', 'Spinal cord injury', 'Peripheral nerve injuries', 'Neurorehabilitation principles'],
  'BOT:RADI6': ['Radiology basics', 'X-ray interpretation basics', 'CT and MRI overview', 'Imaging safety', 'Radiodiagnosis in rehabilitation'],
  'BOT:CLIN6': topicSets.internship,
  'BOT:OTMH7': topicSets.botMentalHealth,
  'BOT:OTNEU7': topicSets.botNeurologicalConditions,
  'BOT:BOAT7': topicSets.botOrthoticsAssistive,
  'BOT:PSM7': ['Preventive medicine', 'Public health system', 'Epidemiology basics', 'National health programs', 'Health education', 'Community participation'],
  'BOT:DAC7': ['Disability models', 'Assessment tools', 'Certification process', 'Functional limitation documentation', 'Benefits and concessions', 'Legal and ethical issues'],
  'BOT:CLIN7': topicSets.internship,
  'BOT:CBR8': topicSets.bptCommunityRehab,
  'BOT:PIOT8': topicSets.botPracticeIssues,
  'BOT:BRM8': topicSets.researchBiostatistics,
  'BOT:ERGO8': topicSets.botErgonomics,
  'BOT:SPSS8': ['SPSS interface', 'Data entry and coding', 'Descriptive statistics', 'Charts and tables', 'Basic tests', 'Exporting results'],
  'BOT:CLIN8': topicSets.internship,

  'BSCN:ENGL101': topicSets.english,
  'BSCN:ANAT105': topicSets.alliedAnatomy,
  'BSCN:PHYS110': topicSets.alliedPhysiology,
  'BSCN:SOCI115': topicSets.sociology,
  'BSCN:PSYC120': ['Introduction to psychology', 'Life span development', 'Motivation and emotion', 'Personality', 'Learning and memory', 'Mental health and adjustment'],
  'BSCN:NNF125-I': topicSets.bscnFoundation1,
  'BSCN:BIOC135': topicSets.alliedBiochemistry,
  'BSCN:NUTR140': ['Nutrients and balanced diet', 'Diet planning', 'Therapeutic diets', 'Nutrition assessment', 'Food safety', 'Nutrition across life cycle'],
  'BSCN:SSCC130-I': ['Self-study planning', 'Co-curricular participation', 'Portfolio documentation', 'Presentation and reflection'],
  'BSCN:NNF125-II': topicSets.bscnFoundation2,
  'BSCN:HNIT145': ['Health informatics basics', 'Hospital information systems', 'Electronic health records', 'Nursing technology', 'Data security and privacy', 'Telehealth'],
  'BSCN:SSCC130-II': ['Guided self-study', 'Library and e-resource use', 'Co-curricular activity report', 'Reflective journal'],
  'BSCN:MICR201': [...topicSets.alliedMicrobiology, 'Infection control and safety in nursing'],
  'BSCN:PHAR205-I': ['General pharmacology', 'Drug administration', 'Autonomic drugs', 'Analgesics and anti-inflammatory drugs', 'Antimicrobials', 'Medication safety'],
  'BSCN:PATH210-I': ['Cell injury and inflammation', 'Hematology basics', 'Common pathological processes', 'Specimen handling', 'Clinical pathology basics'],
  'BSCN:NAHN215-I': topicSets.bscnAdultHealth1,
  'BSCN:SSCC220-I': ['Self-directed learning', 'Clinical learning portfolio', 'Seminar participation', 'Professional activity documentation'],
  'BSCN:PHAR205-II': ['Cardiovascular drugs', 'Respiratory drugs', 'Endocrine drugs', 'Chemotherapy basics', 'Fundamentals of prescribing', 'Drug calculations and safety'],
  'BSCN:PATH210-II': ['Systemic pathology', 'Genetics basics', 'Neoplasia', 'Immunopathology', 'Pathology of common disorders'],
  'BSCN:NAHN225-II': topicSets.bscnAdultHealth2,
  'BSCN:PROF230': ['Professional values', 'Ethics and bioethics', 'Accountability and advocacy', 'Professional conduct', 'Legal issues in nursing'],
  'BSCN:SSCC220-II': ['Self-study review', 'Co-curricular skill activity', 'Case learning reflection', 'Portfolio update'],
  'BSCN:NCHN301-I': topicSets.bscnChildHealth1,
  'BSCN:NMHN305-I': topicSets.bscnMentalHealth1,
  'BSCN:NCOMH310-I': topicSets.bscnCommunity1,
  'BSCN:EDUC315': ['Educational technology', 'Teaching-learning process', 'Lesson planning', 'Clinical teaching', 'Evaluation methods', 'Patient education'],
  'BSCN:NFORN320': ['Forensic nursing introduction', 'Indian legal system', 'Medico-legal cases', 'Evidence preservation', 'Nurse responsibilities and documentation'],
  'BSCN:SSCC325-I': ['Self-study consolidation', 'Co-curricular contribution', 'Student seminar', 'Reflective and activity records'],
  'BSCN:NCHN301-II': topicSets.bscnChildHealth2,
  'BSCN:NMHN305-II': topicSets.bscnMentalHealth2,
  'BSCN:NMLE330': topicSets.bscnManagement,
  'BSCN:NMIDW335-I': topicSets.bscnMidwifery1,
  'BSCN:NCOMH401-II': topicSets.bscnCommunity2,
  'BSCN:NRST405': topicSets.bscnResearch,
  'BSCN:NMIDW410-II': topicSets.bscnMidwifery2,
  'BSCN:INTE415': topicSets.internship,
  'BSCN:INTE420': topicSets.internship,
  'BSCN:INTE425': topicSets.internship,
  'BSCN:INTE430': topicSets.internship,
  'BSCN:INTE435': topicSets.internship,
};

function normalizeTopic(value = '') {
  return String(value).replace(/\s+/g, ' ').trim();
}

export function getSyllabusTopics(curriculumCode, subject = {}) {
  const explicitTopics = Array.isArray(subject.topics) ? subject.topics : [];
  const topics = explicitTopics.length
    ? explicitTopics
    : curriculumCodeTopics[`${curriculumCode}:${subject.code}`] ||
      curriculumCodeTopics[`${curriculumCode}:${subject.name}`] ||
      genericCodeTopics[subject.code] ||
      [];

  return [...new Set(topics.map(normalizeTopic).filter(Boolean))];
}
